version: "3"
services:
  rabbit:
    restart: always
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - dev

networks:
  dev:
    external: true
