server:
  port: 7010

spring:
  application:
    name: batch-manager

  datasource:
    url: "jdbc:h2:mem:mydb"
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console

  rabbitmq:
    addresses: localhost
    port: 5672

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  batch:
    jdbc:
      initialize-schema: EMBEDDED
