server:
  port: 7020

spring:
  application:
    name: batch-worker

  datasource:
    url: "jdbc:h2:mem:workerdb"
    username: sa
#  sql:
#    init:
#      schema-locations:
  h2:
    console:
      enabled: true
      path: /h2-console

  rabbitmq:
    addresses: localhost
    port: 5672

  batch:
    jdbc:
      initialize-schema: EMBEDDED
